version: '3'

services:
  mariadb:
    container_name: mariadb_tmss_auth
    image: bitnami/mariadb:10.6-debian-12
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_USER=${DB_USERNAME}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3300:3306
    volumes:
      - tmpss_volume:/bitnami/mariadb
      
  bitnami:
    container_name: bitnami_tmss_auth
    image: bitnami/laravel:10.3.3-debian-12-r13
    working_dir: /app
    volumes:
      - /mnt/c/software/tmpss_auth:/app
      #- /home/david/Software/tmpss_auth:/app
      # - C:\software\tmpss_auth:/app
    ports:
      # - "0.0.0.0:8001:8001" 
      # - ":::8001:8001"
      - 8001:8080
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}     
    command: >
      sh -c "npm run start"    
    depends_on:
      - mariadb
      
  phpmyadmin:
    container_name: phpmyadmin_tmss_auth
    image: bitnami/phpmyadmin:5.2.1-debian-12-r32
    ports:
      - 8080:8080
      - 443:8443
    depends_on:
      - mariadb
      
volumes:
  tmpss_volume:
    external: true