FROM bitnami/laravel:11.1.4-debian-12-r0

# cd /app
WORKDIR /app

# COPY app bootstrap config database public resources routes storage tests ./
# COPY artisan .env composer.json package.json README.md vite.config.js phpunit.xml ./
COPY . .

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN composer install 
RUN composer update

# Esto se hace luego de montar en contenedor
# RUN php artisan passport:client --password
# RUN php artisan passport:client --personal

# ENV DB_DATABASE=${DB_DATABASE}
# ENV DB_USERNAME=${DB_USERNAME}
# ENV DB_USERNAME=${DB_USERNAME}
# ENV DB_PASSWORD=${DB_PASSWORD}     

CMD php artisan serve --host=0.0.0.0 --port=8000
EXPOSE 8000